API to web interface (draft)
sphericalpm/lektorium pull request #39
Opened 2019-08-09 15:06 UTC by Marge-m

2019-08-09 15:28 UTC, mvartanyan commented on backend/settings.py
> +from os.path import isfile
better not import names directly from stdlib

2019-08-09 15:28 UTC, mvartanyan commented on backend/settings.py
> +from envparse import env
wrong import order

2019-08-09 15:28 UTC, mvartanyan commented on backend/requirements.txt
> +aiohttp==3.5.4
can we have one list of requirements for everything? 

2019-08-09 15:28 UTC, mvartanyan commented on backend/auth/views.py
> +from bson.objectid import ObjectId
where is this from / what is this for? 

2019-08-09 15:28 UTC, mvartanyan commented on backend/auth/models.py
> +# from bson.objectid import ObjectId
remove dead code

2019-08-09 15:28 UTC, mvartanyan commented on backend/auth/views.py
> +def redirect(request, router_name):
I think we have agreed to use type annotations?

2019-08-09 15:28 UTC, mvartanyan commented on backend/auth/views.py
> +def set_session(session, username, request):
a little docstring would be good in this case. I think that I understand what the method does (from reading the code, not from the method name). And I suspect that the choice of method name is not great. But I would prefer not to pass judgment before I see the author's intent :-) 

2019-08-09 15:28 UTC, mvartanyan commented on backend/auth/views.py
> +        return {'content': 'Please enter login or email'}
Let's not have string literals scattered across code

2019-08-09 15:28 UTC, mvartanyan commented on backend/auth/views.py
> +        return response
flake8 it!

2019-08-09 15:38 UTC, mvartanyan commented
Please merge in the master branch so CI can work.

2019-08-13 15:43 UTC, mjecov requested changes

2019-08-13 15:43 UTC, jekoff commented on backend/app.py
> +#! /usr/bin/env python3.7
Not sure that we really need this

2019-08-13 15:43 UTC, jekoff commented on backend/auth/views.py
> +        return response
add new line at the end of the file please!

2019-08-13 15:43 UTC, jekoff commented on backend/routes.py
> +]
add blank line please

2019-09-24 14:27 UTC, apatrushev commented
Are this still relevant?

2019-10-22 16:15 UTC, closed without merging